// C# port of Martin Mitas's md4c Markdown parser Unicode support.
// Ported from md4c/src/md4c.c (Unicode Support section)
//
// AI-HINT: Unicode property tables for case folding, whitespace, and punctuation classification.
// Uses packed range encoding (high bits = range markers) for compact storage.
// Binary search via UnicodeBsearch(). Do not edit tables by hand.

namespace OpenClaw.Shared.Markdown.Md4c
{
    internal struct UnicodeFoldInfo
    {
        public uint[] Codepoints; // length 3
        public int Count;
    }

    internal static class Md4cUnicode
    {
        // Flag constants for range encoding in map arrays.
        private const uint RangeMinFlag = 0x40000000;
        private const uint RangeMaxFlag = 0x80000000;
        private const uint CodepointMask = 0x00ffffff;

        /// <summary>
        /// Binary search over sorted "map" of codepoints. Consecutive sequences
        /// of codepoints may be encoded in the map by just using the
        /// (MIN_CODEPOINT | 0x40000000) and (MAX_CODEPOINT | 0x80000000).
        ///
        /// Returns index of the found record in the map (in the case of ranges,
        /// the minimal value is used); or -1 on failure.
        /// </summary>
        private static int UnicodeBsearch(uint codepoint, uint[] map)
        {
            int beg = 0;
            int end = map.Length - 1;
            while (beg <= end)
            {
                // Pivot may be a range, not just a single value.
                int pivotBeg, pivotEnd;
                pivotBeg = pivotEnd = (beg + end) / 2;
                if ((map[pivotEnd] & RangeMinFlag) != 0)
                    pivotEnd++;
                if ((map[pivotBeg] & RangeMaxFlag) != 0)
                    pivotBeg--;

                if (codepoint < (map[pivotBeg] & CodepointMask))
                    end = pivotBeg - 1;
                else if (codepoint > (map[pivotEnd] & CodepointMask))
                    beg = pivotEnd + 1;
                else
                    return pivotBeg;
            }

            return -1;
        }

        // ---------------------------------------------------------------
        // Whitespace detection
        // ---------------------------------------------------------------

        // Unicode "Zs" category.
        // (generated by scripts/build_whitespace_map.py)
        private static readonly uint[] WhitespaceMap =
        {
            0x0020, 0x00a0, 0x1680, 0x2000 | RangeMinFlag, 0x200a | RangeMaxFlag, 0x202f, 0x205f, 0x3000
        };

        private static bool IsUnicodeWhitespaceImpl(uint codepoint)
        {
            // The ASCII ones are the most frequently used ones, also CommonMark
            // specification requests few more in this range.
            if (codepoint <= 0x7f)
                return IsWhitespace((char)codepoint);

            return UnicodeBsearch(codepoint, WhitespaceMap) >= 0;
        }

        // ---------------------------------------------------------------
        // Punctuation detection
        // ---------------------------------------------------------------

        // Unicode general "P" and "S" categories.
        // (generated by scripts/build_punct_map.py)
        private static readonly uint[] PunctMap =
        {
            0x0021 | RangeMinFlag, 0x002f | RangeMaxFlag,
            0x003a | RangeMinFlag, 0x0040 | RangeMaxFlag,
            0x005b | RangeMinFlag, 0x0060 | RangeMaxFlag,
            0x007b | RangeMinFlag, 0x007e | RangeMaxFlag,
            0x00a1 | RangeMinFlag, 0x00a9 | RangeMaxFlag,
            0x00ab | RangeMinFlag, 0x00ac | RangeMaxFlag,
            0x00ae | RangeMinFlag, 0x00b1 | RangeMaxFlag,
            0x00b4,
            0x00b6 | RangeMinFlag, 0x00b8 | RangeMaxFlag,
            0x00bb, 0x00bf, 0x00d7,
            0x00f7,
            0x02c2 | RangeMinFlag, 0x02c5 | RangeMaxFlag,
            0x02d2 | RangeMinFlag, 0x02df | RangeMaxFlag,
            0x02e5 | RangeMinFlag, 0x02eb | RangeMaxFlag,
            0x02ed,
            0x02ef | RangeMinFlag, 0x02ff | RangeMaxFlag,
            0x0375,
            0x037e,
            0x0384 | RangeMinFlag, 0x0385 | RangeMaxFlag,
            0x0387, 0x03f6, 0x0482,
            0x055a | RangeMinFlag, 0x055f | RangeMaxFlag,
            0x0589 | RangeMinFlag, 0x058a | RangeMaxFlag,
            0x058d | RangeMinFlag, 0x058f | RangeMaxFlag,
            0x05be, 0x05c0, 0x05c3, 0x05c6,
            0x05f3 | RangeMinFlag, 0x05f4 | RangeMaxFlag,
            0x0606 | RangeMinFlag, 0x060f | RangeMaxFlag,
            0x061b,
            0x061d | RangeMinFlag, 0x061f | RangeMaxFlag,
            0x066a | RangeMinFlag, 0x066d | RangeMaxFlag,
            0x06d4, 0x06de, 0x06e9,
            0x06fd | RangeMinFlag, 0x06fe | RangeMaxFlag,
            0x0700 | RangeMinFlag, 0x070d | RangeMaxFlag,
            0x07f6 | RangeMinFlag, 0x07f9 | RangeMaxFlag,
            0x07fe | RangeMinFlag, 0x07ff | RangeMaxFlag,
            0x0830 | RangeMinFlag, 0x083e | RangeMaxFlag,
            0x085e, 0x0888,
            0x0964 | RangeMinFlag, 0x0965 | RangeMaxFlag,
            0x0970,
            0x09f2 | RangeMinFlag, 0x09f3 | RangeMaxFlag,
            0x09fa | RangeMinFlag, 0x09fb | RangeMaxFlag,
            0x09fd, 0x0a76,
            0x0af0 | RangeMinFlag, 0x0af1 | RangeMaxFlag,
            0x0b70,
            0x0bf3 | RangeMinFlag, 0x0bfa | RangeMaxFlag,
            0x0c77, 0x0c7f, 0x0c84, 0x0d4f, 0x0d79, 0x0df4, 0x0e3f,
            0x0e4f,
            0x0e5a | RangeMinFlag, 0x0e5b | RangeMaxFlag,
            0x0f01 | RangeMinFlag, 0x0f17 | RangeMaxFlag,
            0x0f1a | RangeMinFlag, 0x0f1f | RangeMaxFlag,
            0x0f34, 0x0f36, 0x0f38,
            0x0f3a | RangeMinFlag, 0x0f3d | RangeMaxFlag,
            0x0f85,
            0x0fbe | RangeMinFlag, 0x0fc5 | RangeMaxFlag,
            0x0fc7 | RangeMinFlag, 0x0fcc | RangeMaxFlag,
            0x0fce | RangeMinFlag, 0x0fda | RangeMaxFlag,
            0x104a | RangeMinFlag, 0x104f | RangeMaxFlag,
            0x109e | RangeMinFlag, 0x109f | RangeMaxFlag,
            0x10fb,
            0x1360 | RangeMinFlag, 0x1368 | RangeMaxFlag,
            0x1390 | RangeMinFlag, 0x1399 | RangeMaxFlag,
            0x1400,
            0x166d | RangeMinFlag, 0x166e | RangeMaxFlag,
            0x169b | RangeMinFlag, 0x169c | RangeMaxFlag,
            0x16eb | RangeMinFlag, 0x16ed | RangeMaxFlag,
            0x1735 | RangeMinFlag, 0x1736 | RangeMaxFlag,
            0x17d4 | RangeMinFlag, 0x17d6 | RangeMaxFlag,
            0x17d8 | RangeMinFlag, 0x17db | RangeMaxFlag,
            0x1800 | RangeMinFlag, 0x180a | RangeMaxFlag,
            0x1940,
            0x1944 | RangeMinFlag, 0x1945 | RangeMaxFlag,
            0x19de | RangeMinFlag, 0x19ff | RangeMaxFlag,
            0x1a1e | RangeMinFlag, 0x1a1f | RangeMaxFlag,
            0x1aa0 | RangeMinFlag, 0x1aa6 | RangeMaxFlag,
            0x1aa8 | RangeMinFlag, 0x1aad | RangeMaxFlag,
            0x1b5a | RangeMinFlag, 0x1b6a | RangeMaxFlag,
            0x1b74 | RangeMinFlag, 0x1b7e | RangeMaxFlag,
            0x1bfc | RangeMinFlag, 0x1bff | RangeMaxFlag,
            0x1c3b | RangeMinFlag, 0x1c3f | RangeMaxFlag,
            0x1c7e | RangeMinFlag, 0x1c7f | RangeMaxFlag,
            0x1cc0 | RangeMinFlag, 0x1cc7 | RangeMaxFlag,
            0x1cd3,
            0x1fbd,
            0x1fbf | RangeMinFlag, 0x1fc1 | RangeMaxFlag,
            0x1fcd | RangeMinFlag, 0x1fcf | RangeMaxFlag,
            0x1fdd | RangeMinFlag, 0x1fdf | RangeMaxFlag,
            0x1fed | RangeMinFlag, 0x1fef | RangeMaxFlag,
            0x1ffd | RangeMinFlag, 0x1ffe | RangeMaxFlag,
            0x2010 | RangeMinFlag, 0x2027 | RangeMaxFlag,
            0x2030 | RangeMinFlag, 0x205e | RangeMaxFlag,
            0x207a | RangeMinFlag, 0x207e | RangeMaxFlag,
            0x208a | RangeMinFlag, 0x208e | RangeMaxFlag,
            0x20a0 | RangeMinFlag, 0x20c0 | RangeMaxFlag,
            0x2100 | RangeMinFlag, 0x2101 | RangeMaxFlag,
            0x2103 | RangeMinFlag, 0x2106 | RangeMaxFlag,
            0x2108 | RangeMinFlag, 0x2109 | RangeMaxFlag,
            0x2114,
            0x2116 | RangeMinFlag, 0x2118 | RangeMaxFlag,
            0x211e | RangeMinFlag, 0x2123 | RangeMaxFlag,
            0x2125, 0x2127, 0x2129,
            0x212e,
            0x213a | RangeMinFlag, 0x213b | RangeMaxFlag,
            0x2140 | RangeMinFlag, 0x2144 | RangeMaxFlag,
            0x214a | RangeMinFlag, 0x214d | RangeMaxFlag,
            0x214f,
            0x218a | RangeMinFlag, 0x218b | RangeMaxFlag,
            0x2190 | RangeMinFlag, 0x2426 | RangeMaxFlag,
            0x2440 | RangeMinFlag, 0x244a | RangeMaxFlag,
            0x249c | RangeMinFlag, 0x24e9 | RangeMaxFlag,
            0x2500 | RangeMinFlag, 0x2775 | RangeMaxFlag,
            0x2794 | RangeMinFlag, 0x2b73 | RangeMaxFlag,
            0x2b76 | RangeMinFlag, 0x2b95 | RangeMaxFlag,
            0x2b97 | RangeMinFlag, 0x2bff | RangeMaxFlag,
            0x2ce5 | RangeMinFlag, 0x2cea | RangeMaxFlag,
            0x2cf9 | RangeMinFlag, 0x2cfc | RangeMaxFlag,
            0x2cfe | RangeMinFlag, 0x2cff | RangeMaxFlag,
            0x2d70,
            0x2e00 | RangeMinFlag, 0x2e2e | RangeMaxFlag,
            0x2e30 | RangeMinFlag, 0x2e5d | RangeMaxFlag,
            0x2e80 | RangeMinFlag, 0x2e99 | RangeMaxFlag,
            0x2e9b | RangeMinFlag, 0x2ef3 | RangeMaxFlag,
            0x2f00 | RangeMinFlag, 0x2fd5 | RangeMaxFlag,
            0x2ff0 | RangeMinFlag, 0x2fff | RangeMaxFlag,
            0x3001 | RangeMinFlag, 0x3004 | RangeMaxFlag,
            0x3008 | RangeMinFlag, 0x3020 | RangeMaxFlag,
            0x3030,
            0x3036 | RangeMinFlag, 0x3037 | RangeMaxFlag,
            0x303d | RangeMinFlag, 0x303f | RangeMaxFlag,
            0x309b | RangeMinFlag, 0x309c | RangeMaxFlag,
            0x30a0, 0x30fb,
            0x3190 | RangeMinFlag, 0x3191 | RangeMaxFlag,
            0x3196 | RangeMinFlag, 0x319f | RangeMaxFlag,
            0x31c0 | RangeMinFlag, 0x31e3 | RangeMaxFlag,
            0x31ef,
            0x3200 | RangeMinFlag, 0x321e | RangeMaxFlag,
            0x322a | RangeMinFlag, 0x3247 | RangeMaxFlag,
            0x3250,
            0x3260 | RangeMinFlag, 0x327f | RangeMaxFlag,
            0x328a | RangeMinFlag, 0x32b0 | RangeMaxFlag,
            0x32c0 | RangeMinFlag, 0x33ff | RangeMaxFlag,
            0x4dc0 | RangeMinFlag, 0x4dff | RangeMaxFlag,
            0xa490 | RangeMinFlag, 0xa4c6 | RangeMaxFlag,
            0xa4fe | RangeMinFlag, 0xa4ff | RangeMaxFlag,
            0xa60d | RangeMinFlag, 0xa60f | RangeMaxFlag,
            0xa673, 0xa67e,
            0xa6f2 | RangeMinFlag, 0xa6f7 | RangeMaxFlag,
            0xa700 | RangeMinFlag, 0xa716 | RangeMaxFlag,
            0xa720 | RangeMinFlag, 0xa721 | RangeMaxFlag,
            0xa789 | RangeMinFlag, 0xa78a | RangeMaxFlag,
            0xa828 | RangeMinFlag, 0xa82b | RangeMaxFlag,
            0xa836 | RangeMinFlag, 0xa839 | RangeMaxFlag,
            0xa874 | RangeMinFlag, 0xa877 | RangeMaxFlag,
            0xa8ce | RangeMinFlag, 0xa8cf | RangeMaxFlag,
            0xa8f8 | RangeMinFlag, 0xa8fa | RangeMaxFlag,
            0xa8fc,
            0xa92e | RangeMinFlag, 0xa92f | RangeMaxFlag,
            0xa95f,
            0xa9c1 | RangeMinFlag, 0xa9cd | RangeMaxFlag,
            0xa9de | RangeMinFlag, 0xa9df | RangeMaxFlag,
            0xaa5c | RangeMinFlag, 0xaa5f | RangeMaxFlag,
            0xaa77 | RangeMinFlag, 0xaa79 | RangeMaxFlag,
            0xaade | RangeMinFlag, 0xaadf | RangeMaxFlag,
            0xaaf0 | RangeMinFlag, 0xaaf1 | RangeMaxFlag,
            0xab5b,
            0xab6a | RangeMinFlag, 0xab6b | RangeMaxFlag,
            0xabeb, 0xfb29,
            0xfbb2 | RangeMinFlag, 0xfbc2 | RangeMaxFlag,
            0xfd3e | RangeMinFlag, 0xfd4f | RangeMaxFlag,
            0xfdcf,
            0xfdfc | RangeMinFlag, 0xfdff | RangeMaxFlag,
            0xfe10 | RangeMinFlag, 0xfe19 | RangeMaxFlag,
            0xfe30 | RangeMinFlag, 0xfe52 | RangeMaxFlag,
            0xfe54 | RangeMinFlag, 0xfe66 | RangeMaxFlag,
            0xfe68 | RangeMinFlag, 0xfe6b | RangeMaxFlag,
            0xff01 | RangeMinFlag, 0xff0f | RangeMaxFlag,
            0xff1a | RangeMinFlag, 0xff20 | RangeMaxFlag,
            0xff3b | RangeMinFlag, 0xff40 | RangeMaxFlag,
            0xff5b | RangeMinFlag, 0xff65 | RangeMaxFlag,
            0xffe0 | RangeMinFlag, 0xffe6 | RangeMaxFlag,
            0xffe8 | RangeMinFlag, 0xffee | RangeMaxFlag,
            0xfffc | RangeMinFlag, 0xfffd | RangeMaxFlag,
            0x10100 | RangeMinFlag, 0x10102 | RangeMaxFlag,
            0x10137 | RangeMinFlag, 0x1013f | RangeMaxFlag,
            0x10179 | RangeMinFlag, 0x10189 | RangeMaxFlag,
            0x1018c | RangeMinFlag, 0x1018e | RangeMaxFlag,
            0x10190 | RangeMinFlag, 0x1019c | RangeMaxFlag,
            0x101a0,
            0x101d0 | RangeMinFlag, 0x101fc | RangeMaxFlag,
            0x1039f, 0x103d0, 0x1056f, 0x10857,
            0x10877 | RangeMinFlag, 0x10878 | RangeMaxFlag,
            0x1091f, 0x1093f,
            0x10a50 | RangeMinFlag, 0x10a58 | RangeMaxFlag,
            0x10a7f, 0x10ac8,
            0x10af0 | RangeMinFlag, 0x10af6 | RangeMaxFlag,
            0x10b39 | RangeMinFlag, 0x10b3f | RangeMaxFlag,
            0x10b99 | RangeMinFlag, 0x10b9c | RangeMaxFlag,
            0x10ead,
            0x10f55 | RangeMinFlag, 0x10f59 | RangeMaxFlag,
            0x10f86 | RangeMinFlag, 0x10f89 | RangeMaxFlag,
            0x11047 | RangeMinFlag, 0x1104d | RangeMaxFlag,
            0x110bb | RangeMinFlag, 0x110bc | RangeMaxFlag,
            0x110be | RangeMinFlag, 0x110c1 | RangeMaxFlag,
            0x11140 | RangeMinFlag, 0x11143 | RangeMaxFlag,
            0x11174 | RangeMinFlag, 0x11175 | RangeMaxFlag,
            0x111c5 | RangeMinFlag, 0x111c8 | RangeMaxFlag,
            0x111cd, 0x111db,
            0x111dd | RangeMinFlag, 0x111df | RangeMaxFlag,
            0x11238 | RangeMinFlag, 0x1123d | RangeMaxFlag,
            0x112a9,
            0x1144b | RangeMinFlag, 0x1144f | RangeMaxFlag,
            0x1145a | RangeMinFlag, 0x1145b | RangeMaxFlag,
            0x1145d, 0x114c6,
            0x115c1 | RangeMinFlag, 0x115d7 | RangeMaxFlag,
            0x11641 | RangeMinFlag, 0x11643 | RangeMaxFlag,
            0x11660 | RangeMinFlag, 0x1166c | RangeMaxFlag,
            0x116b9,
            0x1173c | RangeMinFlag, 0x1173f | RangeMaxFlag,
            0x1183b,
            0x11944 | RangeMinFlag, 0x11946 | RangeMaxFlag,
            0x119e2,
            0x11a3f | RangeMinFlag, 0x11a46 | RangeMaxFlag,
            0x11a9a | RangeMinFlag, 0x11a9c | RangeMaxFlag,
            0x11a9e | RangeMinFlag, 0x11aa2 | RangeMaxFlag,
            0x11b00 | RangeMinFlag, 0x11b09 | RangeMaxFlag,
            0x11c41 | RangeMinFlag, 0x11c45 | RangeMaxFlag,
            0x11c70 | RangeMinFlag, 0x11c71 | RangeMaxFlag,
            0x11ef7 | RangeMinFlag, 0x11ef8 | RangeMaxFlag,
            0x11f43 | RangeMinFlag, 0x11f4f | RangeMaxFlag,
            0x11fd5 | RangeMinFlag, 0x11ff1 | RangeMaxFlag,
            0x11fff,
            0x12470 | RangeMinFlag, 0x12474 | RangeMaxFlag,
            0x12ff1 | RangeMinFlag, 0x12ff2 | RangeMaxFlag,
            0x16a6e | RangeMinFlag, 0x16a6f | RangeMaxFlag,
            0x16af5,
            0x16b37 | RangeMinFlag, 0x16b3f | RangeMaxFlag,
            0x16b44 | RangeMinFlag, 0x16b45 | RangeMaxFlag,
            0x16e97 | RangeMinFlag, 0x16e9a | RangeMaxFlag,
            0x16fe2, 0x1bc9c, 0x1bc9f,
            0x1cf50 | RangeMinFlag, 0x1cfc3 | RangeMaxFlag,
            0x1d000 | RangeMinFlag, 0x1d0f5 | RangeMaxFlag,
            0x1d100 | RangeMinFlag, 0x1d126 | RangeMaxFlag,
            0x1d129 | RangeMinFlag, 0x1d164 | RangeMaxFlag,
            0x1d16a | RangeMinFlag, 0x1d16c | RangeMaxFlag,
            0x1d183 | RangeMinFlag, 0x1d184 | RangeMaxFlag,
            0x1d18c | RangeMinFlag, 0x1d1a9 | RangeMaxFlag,
            0x1d1ae | RangeMinFlag, 0x1d1ea | RangeMaxFlag,
            0x1d200 | RangeMinFlag, 0x1d241 | RangeMaxFlag,
            0x1d245,
            0x1d300 | RangeMinFlag, 0x1d356 | RangeMaxFlag,
            0x1d6c1, 0x1d6db, 0x1d6fb, 0x1d715, 0x1d735, 0x1d74f, 0x1d76f, 0x1d789, 0x1d7a9,
            0x1d7c3,
            0x1d800 | RangeMinFlag, 0x1d9ff | RangeMaxFlag,
            0x1da37 | RangeMinFlag, 0x1da3a | RangeMaxFlag,
            0x1da6d | RangeMinFlag, 0x1da74 | RangeMaxFlag,
            0x1da76 | RangeMinFlag, 0x1da83 | RangeMaxFlag,
            0x1da85 | RangeMinFlag, 0x1da8b | RangeMaxFlag,
            0x1e14f, 0x1e2ff,
            0x1e95e | RangeMinFlag, 0x1e95f | RangeMaxFlag,
            0x1ecac, 0x1ecb0, 0x1ed2e,
            0x1eef0 | RangeMinFlag, 0x1eef1 | RangeMaxFlag,
            0x1f000 | RangeMinFlag, 0x1f02b | RangeMaxFlag,
            0x1f030 | RangeMinFlag, 0x1f093 | RangeMaxFlag,
            0x1f0a0 | RangeMinFlag, 0x1f0ae | RangeMaxFlag,
            0x1f0b1 | RangeMinFlag, 0x1f0bf | RangeMaxFlag,
            0x1f0c1 | RangeMinFlag, 0x1f0cf | RangeMaxFlag,
            0x1f0d1 | RangeMinFlag, 0x1f0f5 | RangeMaxFlag,
            0x1f10d | RangeMinFlag, 0x1f1ad | RangeMaxFlag,
            0x1f1e6 | RangeMinFlag, 0x1f202 | RangeMaxFlag,
            0x1f210 | RangeMinFlag, 0x1f23b | RangeMaxFlag,
            0x1f240 | RangeMinFlag, 0x1f248 | RangeMaxFlag,
            0x1f250 | RangeMinFlag, 0x1f251 | RangeMaxFlag,
            0x1f260 | RangeMinFlag, 0x1f265 | RangeMaxFlag,
            0x1f300 | RangeMinFlag, 0x1f6d7 | RangeMaxFlag,
            0x1f6dc | RangeMinFlag, 0x1f6ec | RangeMaxFlag,
            0x1f6f0 | RangeMinFlag, 0x1f6fc | RangeMaxFlag,
            0x1f700 | RangeMinFlag, 0x1f776 | RangeMaxFlag,
            0x1f77b | RangeMinFlag, 0x1f7d9 | RangeMaxFlag,
            0x1f7e0 | RangeMinFlag, 0x1f7eb | RangeMaxFlag,
            0x1f7f0,
            0x1f800 | RangeMinFlag, 0x1f80b | RangeMaxFlag,
            0x1f810 | RangeMinFlag, 0x1f847 | RangeMaxFlag,
            0x1f850 | RangeMinFlag, 0x1f859 | RangeMaxFlag,
            0x1f860 | RangeMinFlag, 0x1f887 | RangeMaxFlag,
            0x1f890 | RangeMinFlag, 0x1f8ad | RangeMaxFlag,
            0x1f8b0 | RangeMinFlag, 0x1f8b1 | RangeMaxFlag,
            0x1f900 | RangeMinFlag, 0x1fa53 | RangeMaxFlag,
            0x1fa60 | RangeMinFlag, 0x1fa6d | RangeMaxFlag,
            0x1fa70 | RangeMinFlag, 0x1fa7c | RangeMaxFlag,
            0x1fa80 | RangeMinFlag, 0x1fa88 | RangeMaxFlag,
            0x1fa90 | RangeMinFlag, 0x1fabd | RangeMaxFlag,
            0x1fabf | RangeMinFlag, 0x1fac5 | RangeMaxFlag,
            0x1face | RangeMinFlag, 0x1fadb | RangeMaxFlag,
            0x1fae0 | RangeMinFlag, 0x1fae8 | RangeMaxFlag,
            0x1faf0 | RangeMinFlag, 0x1faf8 | RangeMaxFlag,
            0x1fb00 | RangeMinFlag, 0x1fb92 | RangeMaxFlag,
            0x1fb94 | RangeMinFlag, 0x1fbca | RangeMaxFlag,
        };

        private static bool IsUnicodePunctImpl(uint codepoint)
        {
            // The ASCII ones are the most frequently used ones, also CommonMark
            // specification requests few more in this range.
            if (codepoint <= 0x7f)
                return IsPunct((char)codepoint);

            return UnicodeBsearch(codepoint, PunctMap) >= 0;
        }

        // ---------------------------------------------------------------
        // Case folding
        // ---------------------------------------------------------------

        // Unicode case folding maps.
        // (generated by scripts/build_folding_map.py)

        private static readonly uint[] FoldMap1 =
        {
            0x0041 | RangeMinFlag, 0x005a | RangeMaxFlag,
            0x00b5,
            0x00c0 | RangeMinFlag, 0x00d6 | RangeMaxFlag,
            0x00d8 | RangeMinFlag, 0x00de | RangeMaxFlag,
            0x0100 | RangeMinFlag, 0x012e | RangeMaxFlag,
            0x0132 | RangeMinFlag, 0x0136 | RangeMaxFlag,
            0x0139 | RangeMinFlag, 0x0147 | RangeMaxFlag,
            0x014a | RangeMinFlag, 0x0176 | RangeMaxFlag,
            0x0178,
            0x0179 | RangeMinFlag, 0x017d | RangeMaxFlag,
            0x017f, 0x0181, 0x0182, 0x0184, 0x0186, 0x0187, 0x0189, 0x018a, 0x018b,
            0x018e, 0x018f, 0x0190, 0x0191, 0x0193, 0x0194, 0x0196, 0x0197, 0x0198,
            0x019c, 0x019d, 0x019f,
            0x01a0 | RangeMinFlag, 0x01a4 | RangeMaxFlag,
            0x01a6, 0x01a7, 0x01a9, 0x01ac, 0x01ae, 0x01af, 0x01b1, 0x01b2,
            0x01b3, 0x01b5, 0x01b7, 0x01b8, 0x01bc, 0x01c4, 0x01c5, 0x01c7, 0x01c8,
            0x01ca,
            0x01cb | RangeMinFlag, 0x01db | RangeMaxFlag,
            0x01de | RangeMinFlag, 0x01ee | RangeMaxFlag,
            0x01f1, 0x01f2, 0x01f4, 0x01f6, 0x01f7,
            0x01f8 | RangeMinFlag, 0x021e | RangeMaxFlag,
            0x0220,
            0x0222 | RangeMinFlag, 0x0232 | RangeMaxFlag,
            0x023a, 0x023b, 0x023d, 0x023e, 0x0241, 0x0243, 0x0244, 0x0245,
            0x0246 | RangeMinFlag, 0x024e | RangeMaxFlag,
            0x0345, 0x0370, 0x0372, 0x0376, 0x037f,
            0x0386,
            0x0388 | RangeMinFlag, 0x038a | RangeMaxFlag,
            0x038c, 0x038e, 0x038f,
            0x0391 | RangeMinFlag, 0x03a1 | RangeMaxFlag,
            0x03a3 | RangeMinFlag, 0x03ab | RangeMaxFlag,
            0x03c2, 0x03cf, 0x03d0, 0x03d1, 0x03d5, 0x03d6,
            0x03d8 | RangeMinFlag, 0x03ee | RangeMaxFlag,
            0x03f0, 0x03f1, 0x03f4, 0x03f5, 0x03f7, 0x03f9, 0x03fa,
            0x03fd | RangeMinFlag, 0x03ff | RangeMaxFlag,
            0x0400 | RangeMinFlag, 0x040f | RangeMaxFlag,
            0x0410 | RangeMinFlag, 0x042f | RangeMaxFlag,
            0x0460 | RangeMinFlag, 0x0480 | RangeMaxFlag,
            0x048a | RangeMinFlag, 0x04be | RangeMaxFlag,
            0x04c0,
            0x04c1 | RangeMinFlag, 0x04cd | RangeMaxFlag,
            0x04d0 | RangeMinFlag, 0x052e | RangeMaxFlag,
            0x0531 | RangeMinFlag, 0x0556 | RangeMaxFlag,
            0x10a0 | RangeMinFlag, 0x10c5 | RangeMaxFlag,
            0x10c7, 0x10cd,
            0x13f8 | RangeMinFlag, 0x13fd | RangeMaxFlag,
            0x1c80, 0x1c81, 0x1c82, 0x1c83, 0x1c84, 0x1c85, 0x1c86, 0x1c87, 0x1c88,
            0x1c90 | RangeMinFlag, 0x1cba | RangeMaxFlag,
            0x1cbd | RangeMinFlag, 0x1cbf | RangeMaxFlag,
            0x1e00 | RangeMinFlag, 0x1e94 | RangeMaxFlag,
            0x1e9b,
            0x1ea0 | RangeMinFlag, 0x1efe | RangeMaxFlag,
            0x1f08 | RangeMinFlag, 0x1f0f | RangeMaxFlag,
            0x1f18 | RangeMinFlag, 0x1f1d | RangeMaxFlag,
            0x1f28 | RangeMinFlag, 0x1f2f | RangeMaxFlag,
            0x1f38 | RangeMinFlag, 0x1f3f | RangeMaxFlag,
            0x1f48 | RangeMinFlag, 0x1f4d | RangeMaxFlag,
            0x1f59, 0x1f5b, 0x1f5d, 0x1f5f,
            0x1f68 | RangeMinFlag, 0x1f6f | RangeMaxFlag,
            0x1fb8, 0x1fb9, 0x1fba, 0x1fbb, 0x1fbe,
            0x1fc8 | RangeMinFlag, 0x1fcb | RangeMaxFlag,
            0x1fd8, 0x1fd9, 0x1fda, 0x1fdb,
            0x1fe8, 0x1fe9, 0x1fea, 0x1feb, 0x1fec,
            0x1ff8, 0x1ff9, 0x1ffa, 0x1ffb,
            0x2126, 0x212a, 0x212b, 0x2132,
            0x2160 | RangeMinFlag, 0x216f | RangeMaxFlag,
            0x2183,
            0x24b6 | RangeMinFlag, 0x24cf | RangeMaxFlag,
            0x2c00 | RangeMinFlag, 0x2c2f | RangeMaxFlag,
            0x2c60, 0x2c62, 0x2c63, 0x2c64,
            0x2c67 | RangeMinFlag, 0x2c6b | RangeMaxFlag,
            0x2c6d, 0x2c6e, 0x2c6f, 0x2c70, 0x2c72, 0x2c75, 0x2c7e, 0x2c7f,
            0x2c80 | RangeMinFlag, 0x2ce2 | RangeMaxFlag,
            0x2ceb, 0x2ced, 0x2cf2,
            0xa640 | RangeMinFlag, 0xa66c | RangeMaxFlag,
            0xa680 | RangeMinFlag, 0xa69a | RangeMaxFlag,
            0xa722 | RangeMinFlag, 0xa72e | RangeMaxFlag,
            0xa732 | RangeMinFlag, 0xa76e | RangeMaxFlag,
            0xa779, 0xa77b, 0xa77d,
            0xa77e | RangeMinFlag, 0xa786 | RangeMaxFlag,
            0xa78b, 0xa78d, 0xa790, 0xa792,
            0xa796 | RangeMinFlag, 0xa7a8 | RangeMaxFlag,
            0xa7aa, 0xa7ab, 0xa7ac, 0xa7ad, 0xa7ae, 0xa7b0, 0xa7b1, 0xa7b2,
            0xa7b3,
            0xa7b4 | RangeMinFlag, 0xa7c2 | RangeMaxFlag,
            0xa7c4, 0xa7c5, 0xa7c6, 0xa7c7, 0xa7c9, 0xa7d0, 0xa7d6, 0xa7d8, 0xa7f5,
            0xab70 | RangeMinFlag, 0xabbf | RangeMaxFlag,
            0xff21 | RangeMinFlag, 0xff3a | RangeMaxFlag,
            0x10400 | RangeMinFlag, 0x10427 | RangeMaxFlag,
            0x104b0 | RangeMinFlag, 0x104d3 | RangeMaxFlag,
            0x10570 | RangeMinFlag, 0x1057a | RangeMaxFlag,
            0x1057c | RangeMinFlag, 0x1058a | RangeMaxFlag,
            0x1058c | RangeMinFlag, 0x10592 | RangeMaxFlag,
            0x10594, 0x10595,
            0x10c80 | RangeMinFlag, 0x10cb2 | RangeMaxFlag,
            0x118a0 | RangeMinFlag, 0x118bf | RangeMaxFlag,
            0x16e40 | RangeMinFlag, 0x16e5f | RangeMaxFlag,
            0x1e900 | RangeMinFlag, 0x1e921 | RangeMaxFlag,
        };

        private static readonly uint[] FoldMap1Data =
        {
            0x0061, 0x007a, 0x03bc, 0x00e0, 0x00f6, 0x00f8, 0x00fe, 0x0101, 0x012f, 0x0133, 0x0137, 0x013a, 0x0148,
            0x014b, 0x0177, 0x00ff, 0x017a, 0x017e, 0x0073, 0x0253, 0x0183, 0x0185, 0x0254, 0x0188, 0x0256, 0x0257,
            0x018c, 0x01dd, 0x0259, 0x025b, 0x0192, 0x0260, 0x0263, 0x0269, 0x0268, 0x0199, 0x026f, 0x0272, 0x0275,
            0x01a1, 0x01a5, 0x0280, 0x01a8, 0x0283, 0x01ad, 0x0288, 0x01b0, 0x028a, 0x028b, 0x01b4, 0x01b6, 0x0292,
            0x01b9, 0x01bd, 0x01c6, 0x01c6, 0x01c9, 0x01c9, 0x01cc, 0x01cc, 0x01dc, 0x01df, 0x01ef, 0x01f3, 0x01f3,
            0x01f5, 0x0195, 0x01bf, 0x01f9, 0x021f, 0x019e, 0x0223, 0x0233, 0x2c65, 0x023c, 0x019a, 0x2c66, 0x0242,
            0x0180, 0x0289, 0x028c, 0x0247, 0x024f, 0x03b9, 0x0371, 0x0373, 0x0377, 0x03f3, 0x03ac, 0x03ad, 0x03af,
            0x03cc, 0x03cd, 0x03ce, 0x03b1, 0x03c1, 0x03c3, 0x03cb, 0x03c3, 0x03d7, 0x03b2, 0x03b8, 0x03c6, 0x03c0,
            0x03d9, 0x03ef, 0x03ba, 0x03c1, 0x03b8, 0x03b5, 0x03f8, 0x03f2, 0x03fb, 0x037b, 0x037d, 0x0450, 0x045f,
            0x0430, 0x044f, 0x0461, 0x0481, 0x048b, 0x04bf, 0x04cf, 0x04c2, 0x04ce, 0x04d1, 0x052f, 0x0561, 0x0586,
            0x2d00, 0x2d25, 0x2d27, 0x2d2d, 0x13f0, 0x13f5, 0x0432, 0x0434, 0x043e, 0x0441, 0x0442, 0x0442, 0x044a,
            0x0463, 0xa64b, 0x10d0, 0x10fa, 0x10fd, 0x10ff, 0x1e01, 0x1e95, 0x1e61, 0x1ea1, 0x1eff, 0x1f00, 0x1f07,
            0x1f10, 0x1f15, 0x1f20, 0x1f27, 0x1f30, 0x1f37, 0x1f40, 0x1f45, 0x1f51, 0x1f53, 0x1f55, 0x1f57, 0x1f60,
            0x1f67, 0x1fb0, 0x1fb1, 0x1f70, 0x1f71, 0x03b9, 0x1f72, 0x1f75, 0x1fd0, 0x1fd1, 0x1f76, 0x1f77, 0x1fe0,
            0x1fe1, 0x1f7a, 0x1f7b, 0x1fe5, 0x1f78, 0x1f79, 0x1f7c, 0x1f7d, 0x03c9, 0x006b, 0x00e5, 0x214e, 0x2170,
            0x217f, 0x2184, 0x24d0, 0x24e9, 0x2c30, 0x2c5f, 0x2c61, 0x026b, 0x1d7d, 0x027d, 0x2c68, 0x2c6c, 0x0251,
            0x0271, 0x0250, 0x0252, 0x2c73, 0x2c76, 0x023f, 0x0240, 0x2c81, 0x2ce3, 0x2cec, 0x2cee, 0x2cf3, 0xa641,
            0xa66d, 0xa681, 0xa69b, 0xa723, 0xa72f, 0xa733, 0xa76f, 0xa77a, 0xa77c, 0x1d79, 0xa77f, 0xa787, 0xa78c,
            0x0265, 0xa791, 0xa793, 0xa797, 0xa7a9, 0x0266, 0x025c, 0x0261, 0x026c, 0x026a, 0x029e, 0x0287, 0x029d,
            0xab53, 0xa7b5, 0xa7c3, 0xa794, 0x0282, 0x1d8e, 0xa7c8, 0xa7ca, 0xa7d1, 0xa7d7, 0xa7d9, 0xa7f6, 0x13a0,
            0x13ef, 0xff41, 0xff5a, 0x10428, 0x1044f, 0x104d8, 0x104fb, 0x10597, 0x105a1, 0x105a3, 0x105b1, 0x105b3,
            0x105b9, 0x105bb, 0x105bc, 0x10cc0, 0x10cf2, 0x118c0, 0x118df, 0x16e60, 0x16e7f, 0x1e922, 0x1e943,
        };

        private static readonly uint[] FoldMap2 =
        {
            0x00df, 0x0130, 0x0149, 0x01f0, 0x0587, 0x1e96, 0x1e97, 0x1e98, 0x1e99,
            0x1e9a, 0x1e9e, 0x1f50,
            0x1f80 | RangeMinFlag, 0x1f87 | RangeMaxFlag,
            0x1f88 | RangeMinFlag, 0x1f8f | RangeMaxFlag,
            0x1f90 | RangeMinFlag, 0x1f97 | RangeMaxFlag,
            0x1f98 | RangeMinFlag, 0x1f9f | RangeMaxFlag,
            0x1fa0 | RangeMinFlag, 0x1fa7 | RangeMaxFlag,
            0x1fa8 | RangeMinFlag, 0x1faf | RangeMaxFlag,
            0x1fb2, 0x1fb3, 0x1fb4, 0x1fb6, 0x1fbc, 0x1fc2,
            0x1fc3, 0x1fc4, 0x1fc6, 0x1fcc, 0x1fd6, 0x1fe4, 0x1fe6, 0x1ff2, 0x1ff3,
            0x1ff4, 0x1ff6, 0x1ffc, 0xfb00, 0xfb01, 0xfb02, 0xfb05, 0xfb06, 0xfb13,
            0xfb14, 0xfb15, 0xfb16, 0xfb17,
        };

        private static readonly uint[] FoldMap2Data =
        {
            0x0073, 0x0073, 0x0069, 0x0307, 0x02bc, 0x006e, 0x006a, 0x030c, 0x0565, 0x0582, 0x0068, 0x0331, 0x0074, 0x0308,
            0x0077, 0x030a, 0x0079, 0x030a, 0x0061, 0x02be, 0x0073, 0x0073, 0x03c5, 0x0313, 0x1f00, 0x03b9, 0x1f07, 0x03b9,
            0x1f00, 0x03b9, 0x1f07, 0x03b9, 0x1f20, 0x03b9, 0x1f27, 0x03b9, 0x1f20, 0x03b9, 0x1f27, 0x03b9, 0x1f60, 0x03b9,
            0x1f67, 0x03b9, 0x1f60, 0x03b9, 0x1f67, 0x03b9, 0x1f70, 0x03b9, 0x03b1, 0x03b9, 0x03ac, 0x03b9, 0x03b1, 0x0342,
            0x03b1, 0x03b9, 0x1f74, 0x03b9, 0x03b7, 0x03b9, 0x03ae, 0x03b9, 0x03b7, 0x0342, 0x03b7, 0x03b9, 0x03b9, 0x0342,
            0x03c1, 0x0313, 0x03c5, 0x0342, 0x1f7c, 0x03b9, 0x03c9, 0x03b9, 0x03ce, 0x03b9, 0x03c9, 0x0342, 0x03c9, 0x03b9,
            0x0066, 0x0066, 0x0066, 0x0069, 0x0066, 0x006c, 0x0073, 0x0074, 0x0073, 0x0074, 0x0574, 0x0576, 0x0574, 0x0565,
            0x0574, 0x056b, 0x057e, 0x0576, 0x0574, 0x056d,
        };

        private static readonly uint[] FoldMap3 =
        {
            0x0390, 0x03b0, 0x1f52, 0x1f54, 0x1f56, 0x1fb7, 0x1fc7, 0x1fd2, 0x1fd3,
            0x1fd7, 0x1fe2, 0x1fe3, 0x1fe7, 0x1ff7, 0xfb03, 0xfb04,
        };

        private static readonly uint[] FoldMap3Data =
        {
            0x03b9, 0x0308, 0x0301, 0x03c5, 0x0308, 0x0301, 0x03c5, 0x0313, 0x0300, 0x03c5, 0x0313, 0x0301,
            0x03c5, 0x0313, 0x0342, 0x03b1, 0x0342, 0x03b9, 0x03b7, 0x0342, 0x03b9, 0x03b9, 0x0308, 0x0300,
            0x03b9, 0x0308, 0x0301, 0x03b9, 0x0308, 0x0342, 0x03c5, 0x0308, 0x0300, 0x03c5, 0x0308, 0x0301,
            0x03c5, 0x0308, 0x0342, 0x03c9, 0x0342, 0x03b9, 0x0066, 0x0066, 0x0069, 0x0066, 0x0066, 0x006c,
        };

        // Combined fold map list entries: map, data, nCodepoints.
        private struct FoldMapEntry
        {
            public uint[] Map;
            public uint[] Data;
            public int NCodepoints;
        }

        private static readonly FoldMapEntry[] FoldMapList =
        {
            new FoldMapEntry { Map = FoldMap1, Data = FoldMap1Data, NCodepoints = 1 },
            new FoldMapEntry { Map = FoldMap2, Data = FoldMap2Data, NCodepoints = 2 },
            new FoldMapEntry { Map = FoldMap3, Data = FoldMap3Data, NCodepoints = 3 },
        };

        public static void GetUnicodeFoldInfo(uint codepoint, ref UnicodeFoldInfo info)
        {
            if (info.Codepoints == null)
                info.Codepoints = new uint[3];

            // Fast path for ASCII characters.
            if (codepoint <= 0x7f)
            {
                info.Codepoints[0] = codepoint;
                if (codepoint >= 'A' && codepoint <= 'Z')
                    info.Codepoints[0] += 'a' - 'A';
                info.Count = 1;
                return;
            }

            // Try to locate the codepoint in any of the maps.
            for (int i = 0; i < FoldMapList.Length; i++)
            {
                int index = UnicodeBsearch(codepoint, FoldMapList[i].Map);
                if (index >= 0)
                {
                    // Found the mapping.
                    int nCodepoints = FoldMapList[i].NCodepoints;
                    uint[] map = FoldMapList[i].Map;
                    int dataOffset = index * nCodepoints;

                    for (int j = 0; j < nCodepoints; j++)
                        info.Codepoints[j] = FoldMapList[i].Data[dataOffset + j];
                    info.Count = nCodepoints;

                    if (map[index] != codepoint)
                    {
                        // The found mapping maps whole range of codepoints,
                        // i.e. we have to offset info.Codepoints[0] accordingly.
                        uint mapEntry = map[index] & CodepointMask;
                        if (mapEntry + 1 == FoldMapList[i].Data[dataOffset])
                        {
                            // Alternating type of the range.
                            info.Codepoints[0] = codepoint + ((codepoint & 0x1) == (map[index] & 0x1) ? 1u : 0u);
                        }
                        else
                        {
                            // Range to range kind of mapping.
                            info.Codepoints[0] += codepoint - mapEntry;
                        }
                    }

                    return;
                }
            }

            // No mapping found. Map the codepoint to itself.
            info.Codepoints[0] = codepoint;
            info.Count = 1;
        }

        // ---------------------------------------------------------------
        // Character classification helpers (work on C# chars / UTF-16)
        // ---------------------------------------------------------------

        public static bool IsAscii(char ch) => ch <= 127;

        public static bool IsBlank(char ch) => ch == ' ' || ch == '\t';

        public static bool IsNewline(char ch) => ch == '\r' || ch == '\n';

        public static bool IsWhitespace(char ch) => IsBlank(ch) || ch == '\v' || ch == '\f';

        public static bool IsCntrl(char ch) => ch <= 31 || ch == 127;

        public static bool IsPunct(char ch) =>
            (ch >= 33 && ch <= 47) ||
            (ch >= 58 && ch <= 64) ||
            (ch >= 91 && ch <= 96) ||
            (ch >= 123 && ch <= 126);

        public static bool IsUpper(char ch) => ch >= 'A' && ch <= 'Z';

        public static bool IsLower(char ch) => ch >= 'a' && ch <= 'z';

        public static bool IsAlpha(char ch) => IsUpper(ch) || IsLower(ch);

        public static bool IsDigit(char ch) => ch >= '0' && ch <= '9';

        public static bool IsXDigit(char ch) =>
            IsDigit(ch) || (ch >= 'A' && ch <= 'F') || (ch >= 'a' && ch <= 'f');

        public static bool IsAlNum(char ch) => IsAlpha(ch) || IsDigit(ch);

        public static bool IsUnicodeWhitespace(uint codepoint) => IsUnicodeWhitespaceImpl(codepoint);

        public static bool IsUnicodePunct(uint codepoint) => IsUnicodePunctImpl(codepoint);

        // ---------------------------------------------------------------
        // UTF-16 decode helpers (C# strings are UTF-16)
        // ---------------------------------------------------------------

        /// <summary>
        /// Decodes a Unicode codepoint at the given offset in a string.
        /// Handles surrogate pairs. Returns the codepoint and sets charSize
        /// to the number of chars consumed (1 or 2).
        /// </summary>
        public static uint DecodeUnicode(string str, int off, int size, out int charSize)
        {
            if (off < size && char.IsHighSurrogate(str[off]))
            {
                if (off + 1 < size && char.IsLowSurrogate(str[off + 1]))
                {
                    charSize = 2;
                    return (uint)(0x10000 + (((str[off] & 0x3ff) << 10) | (str[off + 1] & 0x3ff)));
                }
            }

            charSize = 1;
            return off < size ? (uint)str[off] : 0u;
        }

        /// <summary>
        /// Decodes the Unicode codepoint immediately before the given offset.
        /// Handles surrogate pairs.
        /// </summary>
        public static uint DecodeUnicodeBefore(string str, int off)
        {
            if (off >= 2 && char.IsHighSurrogate(str[off - 2]) && char.IsLowSurrogate(str[off - 1]))
                return (uint)(0x10000 + (((str[off - 2] & 0x3ff) << 10) | (str[off - 1] & 0x3ff)));

            if (off >= 1)
                return str[off - 1];

            return 0;
        }
    }
}
